### ISSUE TITLE
Issue with "Export task dataset" not applying subset to directory name

### ISSUE THREAD

**Issue by dankernel** [cvat-ai/cvat#6451] opened 2023-07-11 08:32 UTC
### My actions before raising this issue
- [X] Read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)
- [X] Searched [past issues](/issues)

### Steps to Reproduce (for bugs)

1. When exporting a `task` dataset, the subset applied to the task is not reflected in the directory name. 
1. I specified the subset for the task as [Train, Validation, Test, or any arbitrary string], and exported via the UI using actions -> Export task dataset -> YOLO 1.1. 
1. After downloading and unzipping the zip file, the directory name appears as `obj_train_data`. 
1. I expect the directory to be in the format `obj_{subset}_data`, but in all cases, it is compressed as `obj_train_data`.
2. One more, When exporting a project, the first letter of the subset appears in uppercase, like `obj_Train_data`, `obj_Validation_data`, etc. However, when exporting a task, it's in lowercase, such as `obj_train_data`. Could you explain the difference?

### Expected Behaviour

I believe the directory name in the downloaded zip file from the export process should retain the task's subset name in the format of obj_{subset}_data.

### Current Behaviour

The directory is always fixed as obj_train_data, regardless of the subset set in the task.

### Your Environment

I've confirmed the same results for both Kubernetes and Docker Compose. (in linux)
K8s version: v1.26.4
Docker version: 20.10.7, build f0df350
CVAT version: v2.4.3

![image](https://github.com/opencv/cvat/assets/8120041/af9f8b46-5450-4d8c-8376-7e3d1935706a)
I specified a subset.

![image](https://github.com/opencv/cvat/assets/8120041/35ac22d5-e5ac-4134-a863-961e3b842994)
As a result, the subset setting is not applied, and the directory appears as obj_train_data.

![image](https://github.com/opencv/cvat/assets/8120041/9e23757f-957a-42e9-9637-67ee3d8eeed8)
When I export a project, I can see the expected results.

**Comment by zhiltsov-max** [comment] 2023-07-17 08:19
Hi, I think it works as designed now, but it could be a nice export option.

**Comment by dankernel** [comment] 2023-07-17 08:31
@zhiltsov-max 
From the perspective of the MLOps workflow cycle, datasets can continually be added. 
In this case, it is more efficient to export tasks individually rather than exporting the cumulative project as a whole.
Therefore, I believe that task export should also maintain subsets.

I've submitted a pull request(https://github.com/opencv/cvat/pull/6480) regarding this issue. 
Although it works, it is not perfect. 
I hope you could review it and hopefully merge it into the development branch.

**Comment by kirill-sizov** [comment] 2023-07-25 15:06
> Hi, I think it works as designed now, but it could be a nice export option.

@zhiltsov-max But I also find it strange that we get different results for exporting projects and tasks.
If we consider a project as a dataset and a task as a subset of it. Then, in my opinion, it is strange that when we export a project we return directories `train, val`, and when we export a task of this project we return directory `default`. What is the reason for such a design?

**Comment by zhiltsov-max** [comment] 2024-03-19 11:29
Hi, I agree, let's fix it by exporting tasks with "subset" specified into the subset with the required name, to align project and task exports.

**Comment by Pranay38** [comment] 2024-03-20 18:32
Hi, I have reproduced the bug, please assign this to me.
![Uploading Screenshot 2024-03-21 at 12.02.16 AM.png…]()

**Closed** 2024-07-17 08:55 UTC
Labels: dataset, good first issue
