### ISSUE TITLE
confidence threshold in AI Tools

### ISSUE THREAD

**Issue by patcharees** [cvat-ai/cvat#7614] opened 2024-03-15 09:36 UTC
Hi.

I have used my own model for annotations using AI Tools in the sidebar. Is it possible that a user set confidence threshold and send it as a part of request? So that confidence threshold is not fixed/hard coded.

Best regards,
Patcharee

**Comment by bsekachev** [comment] 2024-12-10 18:23
Duplicate of https://github.com/cvat-ai/cvat/issues/8706

**Closed by bsekachev** 2024-12-10 18:23 UTC
Labels: enhancement
