### ISSUE TITLE
"Switch outside" property does not work with the Datumaro format while tracking instances

### ISSUE THREAD

**Issue by Krupal09** [cvat-ai/cvat#7571] opened 2024-03-08 09:50 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://opencv.github.io/cvat/docs/)

### Steps to Reproduce

1. Upload a series of images to the CVAT tool
2. Utilize polygon tracking feature to annotate objects over a set of consecutive images
3. At certain point (for example, at image number 10), opt for "switch outside" property to stop tracking one of the objects
4. Save the annotations in Datumaro format (Menu -> Export job dataset -> Datumaro format)
5. Create a fresh job and upload the same set of images as mentioned in the step 1
6. Upload the annotations generated in step 4
7. Go to the image where the "switch outside" property was opted for (, which was carried out in step 3)
8. The object's annotation polygon still shows up and keeps on penetrating to the further frames

### Expected Behavior

1. Upload a series of images to the CVAT tool
2. Utilize polygon tracking feature to annotate objects over a set of consecutive images
3. At certain point (for example, at image number 10), opt for "switch outside" property to stop tracking one of the objects
4. Save the annotations in Datumaro format (Menu -> Export job dataset -> Datumaro format)
5. Create a fresh job and upload the same set of images as mentioned in the step 1
6. Upload the annotations generated in step 4
7. Go to the image where the "switch outside" property was opted for (, which was carried out in step 3)
---->> 8. The object's annotation polygon should not show up after uploading the saved Datumaro annotation  <<---------

### Context

I am tracking objects over multiple frames and want to remove their annotations from further images when objects are not present on the current frame. The problem with the current state is that all labels from the previous frames are being accumulated to the current frame !

### Environment

Operating system : Linux 22.04
OS type : 64-bit
Using google chrome's latest version
Using CVAT docker on local system

**Comment by bsekachev** [comment] 2024-03-08 09:53
Please, fill the environment.

**Comment by Krupal09** [comment] 2024-03-08 09:54
As it is clearly visible in attached image, annotations from previous images are being accumulated in the current images which is not expected. Any help in this regard would be really appreciated.

![Screenshot from 2024-03-08 10-52-57](https://github.com/opencv/cvat/assets/49275269/8d1e7224-0cbb-4a10-a910-f59e3eb1bc62)

**Comment by Krupal09** [comment] 2024-03-08 10:01
> Please, fill the environment.

@bsekachev Thank you for your quick response ! I have updated the environment field. Kindly let me know if further details are required.

**Comment by Yeek020407** [comment] 2024-03-22 15:09
Hi, I am interested in this issue, could you please assign it to me?

**Comment by Eldies** [comment] 2024-07-17 10:33
Can not reproduce the problem. It seems to be fixed.

**Closed by Eldies** 2024-07-17 10:33 UTC
Labels: bug, need info, good first issue
