### ISSUE TITLE
Error uploading annotations with Yolov8 Detection format

### ISSUE THREAD

**Issue by uxuegu** [cvat-ai/cvat#8546] opened 2024-10-16 06:16 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Expected Behavior

I want to upload new annotations done in Yolov8 to a job that already has some annotations and not deleting anything

### Context

I labelled some images, download the labels on Yolov8 Detection format to train a model. I trained a model to obtain the rest of the labels. When trying to upload those new labels, not only nothing new appears on my dataset but also the ones previously done disappear.  
I have organized the folder to upload the same way as it is downloaded from cvat. A .zip file containing a folder named "labels" where all the labels are organized in .txt files, a data.yaml with all the different classes and a train.txt containing the path of the images. 
The only file that changes is the "labels" folder where now all the labels done by the trained model of Yolov8 appear (data.yaml and train.txt are the ones that are donwload previously from cvat when exporting the job dataset with the labels)

**Comment by zhiltsov-max** [comment] 2024-11-11 10:44
Hi, there is no such option in CVAT yet. 

However you can try to upload a merged dataset in one of the supported formats. This will require you to export the existing annotations, merge them with the other ones you're trying to upload, and upload the merged dataset. For instance, you could use Datumaro for this:

```bash
python -m venv venv
. venv/bin/activate
pip install "datumaro @ git+https://github.com/cvat-ai/datumaro.git@e612d1bfb76a3c3d3d545187338c841a246619fb"
datum patch -o "output_dataset" "annotations/from/cvat/dir:yolov8_detection" "new/annotations/dir:yolov8_detection"
```

Then, you'll need to upload the "output_dataset" back into CVAT.

Duplicate of https://github.com/cvat-ai/cvat/issues/4747

**Closed by zhiltsov-max** 2024-11-11 10:44 UTC
Labels: bug
