### ISSUE TITLE
error in debugging of REST server

### ISSUE THREAD

**Issue by tsune10696** [cvat-ai/cvat#8420] opened 2024-09-09 22:59 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

Hello,
 
I am trying to prepare developement environment according to https://docs.cvat.ai/docs/contributing/development-environment/.
I'm facing the following error in debugging of REST server in vs code.
![30e1501a-88ec-4745-a8cf-e072f2a54489](https://github.com/user-attachments/assets/5426bd9e-f137-4ea9-b77e-1430eb8a1c12)

↓rest server debug error
![7ca7562e-fe86-4d08-a5ce-89d3e2959527](https://github.com/user-attachments/assets/e88db5d0-d056-4d81-b74b-60b6e7346b8d)

■Error Info:
Traceback (most recent call last):
  File "c:\Users\tin.sanoo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\Users\tin.sanoo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\tin.sanoo\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\tin.sanoo\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\tin.sanoo\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\tin.sanoo\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\tin.sanoo\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\tin.sanoo\.vscode\extensions\ms-python.debugpy-2024.10.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "C:\Users\tin.sanoo\cvat/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "c:\Users\tin.sanoo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "c:\Users\tin.sanoo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "c:\Users\tin.sanoo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "c:\Users\tin.sanoo\AppData\Local\Programs\Python\Python310\lib\site-packages\django\apps\registry.py", line 124, in populate
    app_config.ready()
  File "C:\Users\tin.sanoo\cvat\cvat\apps\quality_control\apps.py", line 26, in ready
    from . import signals  # pylint: disable=unused-import
  File "C:\Users\tin.sanoo\cvat\cvat\apps\quality_control\signals.py", line 10, in <module>
    from cvat.apps.quality_control import quality_reports as qc
  File "C:\Users\tin.sanoo\cvat\cvat\apps\quality_control\quality_reports.py", line 27, in <module>
    from cvat.apps.dataset_manager.bindings import (
  File "C:\Users\tin.sanoo\cvat\cvat\apps\dataset_manager\bindings.py", line 25, in <module>
    from datumaro.components.extractor import Importer
ModuleNotFoundError: No module named 'datumaro.components.extractor'

■My installed apps list:
Package                     Version

aiohappyeyeballs          2.4.0      
aiohttp                   3.10.5     
aiohttp-retry             2.8.3      
aiosignal                 1.3.1      
amqp                      5.2.0      
annotated-types           0.7.0      
antlr4-python3-runtime    4.9.3      
appdirs                   1.4.4      
asgiref                   3.8.1      
async-timeout             4.0.3      
asyncssh                  2.17.0     
atpublic                  5.0        
attrs                     24.2.0
autopep8                  2.3.1
av                        12.0.0
azure-core                1.30.2
azure-storage-blob        12.13.0
billiard                  4.2.0
boto3                     1.35.14
botocore                  1.35.14
Brotli                    1.1.0
cachetools                5.5.0
celery                    5.4.0
certifi                   2024.8.30
cffi                      1.17.1
charset-normalizer        3.3.2
click                     8.1.7
click-didyoumean          0.3.1
click-plugins             1.1.1
click-repl                0.3.0
colorama                  0.4.6
configobj                 5.0.8
contourpy                 1.3.0
cryptography              43.0.1
cuda-python               12.6.0
cycler                    0.12.1
datumaro                  1.8.0
defusedxml                0.7.1
Deprecated                1.2.14
dictdiffer                0.9.0
diskcache                 5.6.3
distro                    1.9.0
dj-pagination             2.5.0
dj-rest-auth              6.0.0
Django                    5.1.1
django-allauth            64.2.1
django-appconf            1.0.6
django-compressor         4.3.1
django-cors-headers       1.1.0
django-crum               0.7.9
django-extensions         3.2.3
django-filter             24.3
django-health-check       3.18.3
django-rq                 2.10.2
django-sendfile           0.3.11
django-sendfile2          0.7.1
django-silk               5.2.0
djangorestframework       3.15.2
dpath                     2.2.0
drf-spectacular           0.27.2
dulwich                   0.22.1
dvc                       3.49.0
dvc-data                  3.15.2
dvc-http                  2.32.0
dvc-objects               5.1.0
dvc-render                1.0.2
dvc-studio-client         0.21.0
dvc-task                  0.4.0
entrypoints               0.4
filelock                  3.16.0
flatten-dict              0.4.2
flufl.lock                7.1.1
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2024.9.0
funcy                     2.0
furl                      2.1.0
gevent                    24.2.1
geventhttpclient          2.0.2
gitdb                     4.0.11
GitPython                 3.1.43
google-api-core           2.19.2
google-auth               2.34.0
google-cloud-core         2.4.1
google-cloud-storage      1.42.0
google-crc32c             1.5.0
google-resumable-media    2.7.2
googleapis-common-protos  1.65.0
gprof2dot                 2024.6.6
grandalf                  0.8
greenlet                  3.0.3
grpcio                    1.66.1
gto                       1.7.1
h5py                      3.11.0
huggingface-hub           0.24.6
hydra-core                1.3.2
idna                      3.8
imagesize                 1.4.1
importlib_resources       6.4.4
inflection                0.5.1
isodate                   0.6.1
iterative-telemetry       0.0.8
jmespath                  0.10.0
joblib                    1.4.2
json-stream               2.3.2
json-stream-rs-tokenizer  0.4.26
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.7
kombu                     5.4.0
limits                    3.13.0
lxml                      5.3.0
markdown-it-py            3.0.0
matplotlib                3.9.2
mdurl                     0.1.2
msrest                    0.7.1
multidict                 6.0.5
networkx                  3.1
nibabel                   5.2.1
nltk                      3.9.1
numpy                     1.26.4
oauthlib                  3.2.2
omegaconf                 2.3.0
opencv-python             4.10.0.84
openvino                  2024.3.0
openvino-dev              2024.3.0
openvino-telemetry        2024.1.0
orderedmultidict          1.0.1
orjson                    3.10.5
ovmsclient                2023.1
packaging                 24.1
pandas                    2.2.2
pathspec                  0.12.1
pillow                    10.4.0
pip                       24.2
platformdirs              3.11.0
prompt_toolkit            3.0.47
proto-plus                1.24.0
protobuf                  4.25.4
psutil                    5.9.4
psycopg                   3.2.1
psycopg2                  2.9.9
psycopg2-binary           2.9.5
pyarrow                   17.0.0
pyasn1                    0.6.0
pyasn1_modules            0.4.0
pycocotools               2.0.8
pycodestyle               2.12.1
pycparser                 2.22
pydantic                  2.9.0
pydantic_core             2.23.2
pydot                     3.0.1
pyemd                     1.0.0
pygit2                    1.15.1
Pygments                  2.18.0
pygtrie                   2.5.0
pylogbeat                 2.0.1
pyparsing                 3.1.4
python-dateutil           2.9.0.post0
python-logstash-async     3.0.0
python-rapidjson          1.20
pytz                      2024.1
pywin32                   306
PyYAML                    6.0.1
rcssmin                   1.1.1
redis                     5.0.8
referencing               0.35.1
regex                     2024.7.24
requests                  2.32.3
requests-oauthlib         2.0.0
rich                      13.8.0
rjsmin                    1.2.1
rpds-py                   0.20.0
rq                        1.16.0
rsa                       4.9
ruamel.yaml               0.18.6
ruamel.yaml.clib          0.2.8
s3transfer                0.10.2
scikit-learn              1.5.1
scipy                     1.14.1
scmrepo                   3.3.7
semver                    3.0.2
setuptools                58.1.0
shapely                   2.0.6
shellingham               1.5.4
shortuuid                 1.0.13
shtab                     1.7.1
six                       1.16.0
smmap                     5.0.1
sqlparse                  0.5.1
sqltrie                   0.11.1
tabulate                  0.9.0
tensorboardX              2.6.2.2
threadpoolctl             3.5.0
tokenizers                0.20.0
tokenizers                0.20.0
tomli                     2.0.1
tomlkit                   0.13.2
tqdm                      4.66.5
tqdm                      4.66.5
tritonclient              2.49.0
typer                     0.12.5
typing_extensions         4.12.2
tzdata                    2024.1
uritemplate               4.1.1
urllib3                   2.2.2
vine                      5.1.0
voluptuous                0.15.2
wcwidth                   0.2.13
wrapt                     1.16.0
yarl                      1.11.0
zc.lockfile               3.0.post1
zope.event                5.0
zope.interface            7.0.3

@azhavoro

**Comment by azhavoro** [comment] 2024-09-10 07:09
Duplicate of #8408 

Please follow the guide https://docs.cvat.ai/docs/contributing/development-environment/#note-for-windows-users
and note that the guide only supports WSL2, not the native windows environment.

**Closed by azhavoro** 2024-09-10 07:09 UTC
Labels: bug
