### ISSUE TITLE
Cannot read properties of null (reading 'annotations')

### ISSUE THREAD

**Issue by bsekachev** [cvat-ai/cvat#7363] opened 2024-01-17 08:29 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

1. Open a job
2. Upload annotations to the job
3. Go to task page before upload is done
![image](https://github.com/opencv/cvat/assets/40690378/1499849e-e555-492b-a924-398df2779deb)

### Environment

```Markdown
v2.10.0
```

**Comment by MKBenjie** [comment] 2024-03-21 14:49
I'm interested in this issue and am ready to tackle it. Could you please assign it to me?

**Comment by MKBenjie** [comment] 2024-03-23 11:51
I was able to reproduce this bug.

## Issue

When I navigate away from the page while uploading annotations the message "Cannot read properties of null (reading 'annotations')" along with "Annotations have been loaded to the task" are displayed to the user. This error occurs because the FETCH_ANNOTATIONS_FAILED action is triggered since annotations have to be loaded and fetched yet I  navigated away from the page, even though the annotations loading process is still a success. This leads to unnecessary error message being displayed.

## Root Cause

The root cause of the issue is that the FETCH_ANNOTATIONS_FAILED action is dispatched without considering the possibility of navigation interruption during the annotations fetching process.

## Proposed Solution

To resolve this issue, I will implement a mechanism to detect navigation interruptions during the annotations fetching process. This involves modifying the fetchAnnotationsAsync function to handle navigation interruptions by checking if the interruption occurred before dispatching the FETCH_ANNOTATIONS_FAILED action. Additionally, I will update the error handling logic to consider navigation interruptions so that the warming isn't displayed if it was due to navigation interruptions.

**Comment by nmanovic** [comment] 2024-03-25 14:54
@MKBenjie , please send us a PR which solves the issue. Could you please add a test as well?

**Comment by MKBenjie** [comment] 2024-03-30 03:26
Created the PR and added a test as well

**Comment by nmanovic** [comment] 2024-04-01 14:46
@MKBenjie , could you please share a link on the PR? I cannot find it.

**Comment by bsekachev** [comment] 2024-04-01 15:12
@nmanovic 

https://github.com/opencv/cvat/pull/7704

**Closed** 2024-05-08 06:07 UTC
Labels: bug, good first issue
