### ISSUE TITLE
Error when trying to export task dataset  (AssertionError)

### ISSUE THREAD

**Issue by ragahdtareg** [cvat-ai/cvat#7097] opened 2023-11-05 06:07 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://github.com/cvat-ai/cvat/tree/master#documentation)

### Steps to Reproduce

I am trying to export data set in **YOLO 1.1** format but I faced the error multiple times, I can't export task dataset 

### Expected Behavior

This is the error showing everytime I tried to export task dataset 

Could not export dataset for the [task 19](http://localhost:8080/tasks/19)

Error: Request failed with status code 500. "AssertionError\n".

### Context

This issue blocked me a long time from my work, i need to solve it right now please.

### Environment

```Markdown
Server version: 2.8.0

Core version: 11.1.0

Canvas version: 2.17.5

UI version: 1.56.1
```

**Comment by bsekachev** [comment] 2023-11-06 06:28
How can we reproduce the issue?

**Comment by zhiltsov-max** [comment] 2023-11-06 12:47
Hi, please attach logs from the command output: `docker logs cvat_worker_export`.

**Comment by kedarps** [comment] 2023-11-07 15:20
We are facing the same error. We have a simple object detection task and export using the 'CVAT for images 1.1' works, but using 'PASCAL VOC 1.1' gives `AssertionError`. Here is the log:

```
2023-11-07 15:09:03,945 DEBG 'rqworker-export-1' stderr output:
[2023-11-07 15:09:03,944] ERROR cvat.apps.dataset_manager.views: [Job.id=2] [cvat.apps.dataset_manager.views @ export]: exception occurred
Traceback (most recent call last):
  File "/home/django/cvat/apps/dataset_manager/views.py", line 85, in export
    export_fn(db_instance.id, temp_file, dst_format,
  File "/home/django/cvat/apps/dataset_manager/task.py", line 855, in export_job
    job.export(f, exporter, host=server_url, save_images=save_images)
  File "/home/django/cvat/apps/dataset_manager/task.py", line 685, in export
    exporter(dst_file, temp_dir, job_data, **options)
  File "/home/django/cvat/apps/dataset_manager/formats/registry.py", line 36, in __call__
    f_or_cls(*args, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/formats/pascal_voc.py", line 23, in _export
    dataset = Dataset.from_extractors(GetCVATDataExtractor(
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 1614, in GetCVATDataExtractor
    return CvatTaskOrJobDataExtractor(instance_data, **kwargs)
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 1388, in __init__
    self._categories = self._load_categories(instance_meta['labels'])
  File "/home/django/cvat/apps/dataset_manager/bindings.py", line 1332, in _load_categories
    label_id = label_categories.add(label['name'], label.get('parent'))
  File "/opt/venv/lib/python3.10/site-packages/datumaro/components/annotation.py", line 161, in add
    assert key not in self._indices
AssertionError
```

**Comment by zhiltsov-max** [comment] 2023-11-08 09:32
@kedarps, do you know how we can reproduce the problem? A task backup or task label configuration would be helpful.

**Comment by kedarps** [comment] 2023-11-08 13:49
Yes sure, here is the Task Backup zip file: 
[ObjDetect_TaskBackup.zip](https://github.com/opencv/cvat/files/13297336/ObjDetect_TaskBackup.zip)

**Comment by PMazarovich** [comment] 2023-11-15 13:42
@bsekachev we have the same for custom format
the thing is that you're allowed to export annotations in cvat for video format, import this file to another task and then when trying to export the stuff from new task - asserion error. 
I can provide a file if needed

**Comment by azhavoro** [comment] 2024-09-06 11:10
The problem seems to have been resolved in one of the releases.  The only provided example of a task with incorrect export is correctly exported in Yolo format for now

**Closed by azhavoro** 2024-09-06 11:10 UTC
Labels: bug, need info, good first issue

**Comment by PMazarovich** [comment] 2024-09-06 14:24
@azhavoro , this is not resolved. I will create a new issue

**Comment by PMazarovich** [comment] 2024-09-06 14:46
https://github.com/cvat-ai/cvat/issues/8411

**Comment by zhiltsov-max** [comment] 2024-09-06 15:58
It seems that there were 2 or 3 different errors in this discussion:

1. The one reported initially and also maybe by @PMazarovich.
It seems to be related to https://github.com/cvat-ai/cvat/issues/6779

3. https://github.com/cvat-ai/cvat/issues/7097#issuecomment-1798853092
> We are facing the same error. We have a simple object detection task and export using the 'CVAT for images 1.1' works, but using 'PASCAL VOC 1.1' gives AssertionError. Here is the log: ...

It should have been fixed in https://github.com/cvat-ai/cvat/pull/8262.
