### ISSUE TITLE
HTTP response body: "Export has not finished"

### ISSUE THREAD

**Issue by TimotheeWrightFicha** [cvat-ai/cvat#8045] opened 2024-06-18 15:07 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

```
configuration = Configuration(
        host=main_url,
        username=user_name,
        password=password,
    )

    api_client = ApiClient(configuration)
    error = False
    while True:
        try:
            (_, response) = api_client.tasks_api.retrieve_dataset(
                id=task_id,
                format="COCO 1.0",
                action="download",
                location="local",
                _parse_response=False,
            )
            if response.status == 200:
                break
        except Exception as e:
            print(f"An error occurred: {e}")
            error = True
            break

    data_name = f'Data_{task_id}_{datetime.now().strftime("%Y_%m_%d_%H_%M")}.zip'

    if not error:
        # Save the resulting file
        with open(data_name, "wb") as output_file:
            output_file.write(response.data)
        return data_name

    else:
        return None
```

Got the error: 
```
An error occurred: Status Code: 400
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Allow': 'GET, HEAD, OPTIONS', 'Content-Length': '25', 'Content-Type': 'application/vnd.cvat+json', 'Cross-Origin-Opener-Policy': 'same-origin', 'Date': 'Tue, 18 Jun 2024 15:03:51 GMT', 'Referrer-Policy': 'same-origin, strict-origin-when-cross-origin', 'Server': 'nginx', 'Vary': 'Accept, Origin, Cookie', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-Frame-Options': 'DENY', 'X-Request-Id': '9444c619-b8e7-44db-a42f-0af10e1b19f3'})
HTTP response body: "Export has not finished"
```

### Expected Behavior

The same code used to work to export data out of CVAT. 

### Possible Solution

I saw [this commit](https://github.com/cvat-ai/cvat/pull/7864) linked to download of dataset was done since the last time we run our code. Maybe it's coming from there ?

### Context

Trying to export tasks from CVAT from python

**Comment by bsekachev** [comment] 2024-06-19 05:42
Duplicate of #https://github.com/cvat-ai/cvat/issues/8041

**Closed by bsekachev** 2024-06-19 05:42 UTC
Labels: bug

**Comment by darkgod1kandarp** [comment] 2024-06-19 21:10
Hello @bsekachev  I think so CVAT SDK is not supporting this behaviour , it does not allow **action** values to be set other than "download"  .
`api_client.tasks_api.retrieve_dataset(
                id=task_id,
                format="COCO 1.0",
                action="download",
                location="local",
                _parse_response=False,
            )
`
So we have to manually write request to download dataset. Can you please correct me if I am wrong?
`
    while True:
        try:
            response =  re.get(url, auth=('******', '******'))
            print(response.status_code)

            if response.status_code == 202:
                print("Dataset is being prepared.")
                continue
            elif response.status_code == 201:
                url =  url + "&action=download"
                print("File path has been created.")
            elif response.status_code == 200:

                data_name = f'Data_{task_id}_{datetime.now().strftime("%Y_%m_%d_%H_%M")}.zip'
                print(data_name)
                with open(data_name, "wb") as output_file:
                    output_file.write(response.content)

                break
            else:
                print(f"An error occurred: {response.status_code}")
                error = True
                break

        except Exception as e:
            print(f"An error occurred: {e}")
            error = True
            break
`

**Comment by bsekachev** [comment] 2024-06-20 06:13
> it does not allow action values to be set other than "download" .

Try to omit this parameter, you do not need to specify other values.

**Comment by stiv-yakovenko** [comment] 2025-03-23 06:15
This api now is deprecated, here is what i get now:

HTTP response body: This endpoint is no longer supported.
To initiate the export process, use POST /api/tasks/id/dataset/export?save_images=True.
To check the process status, use GET /api/requests/rq_id,
where rq_id is obtained from the response of the previous request.
To download the prepared file, use the result_url obtained from the response of the previous request.
