### ISSUE TITLE
Issue with exporting segmentation masks in COCO format

### ISSUE THREAD

**Issue by camkisailus** [cvat-ai/cvat#7938] opened 2024-05-23 18:26 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create multi tasks using mp4's.
2. Set some jobs as Train subset and others as Test subset.
3. Annotate some frames with segmentation masks
4. Export the entire project dataset 

I then use the pycocotools library to visualize the dataset. 

I see that the Train set labels match what was annotated:

![image](https://github.com/cvat-ai/cvat/assets/47364146/5413cb7c-b6e3-4555-9a77-050a412ca94b)
![image](https://github.com/cvat-ai/cvat/assets/47364146/17c9527b-32eb-4eac-a4ca-9a234ecdd6b8)

But, the Test set labels are totally incorrect:
![image](https://github.com/cvat-ai/cvat/assets/47364146/53615c53-7256-434e-8e64-9a2c1360d24a)
![image](https://github.com/cvat-ai/cvat/assets/47364146/d89224f4-d919-4be1-8f6f-f6bb358b3759)

### Expected Behavior

I expect to receive a zip file containing all of the frames in the `images` directory and three annotation files `instances_Train.json`, `instances_Test.json`m and `instances_default.json` in the COCO annotation format. I also expect the annotations and masks to match what is shown in CVAT. 

### Environment

```Markdown
- Local CVAT instance running version 2.5.2 on a native Linux machine.
```

**Comment by bsekachev** [comment] 2024-05-23 20:14
Hello,

First of all, try to use the newest release. 2.5. is quite old. 
If you believe it a bug, send us a minimum reproducing case with the project backup we may use and exact steps we need to perform. 

Thank you.

**Comment by camkisailus** [comment] 2024-05-23 20:59
Hi @bsekachev, are there instructions for upgrading? I cannot figure out how to port my backend (projects, users, etc.) to the new version. 

Second, I have a GDrive [link](https://drive.google.com/file/d/1NWT0JdxehD5Mq-H7VLLL1o4VqjHpE_yP/view?usp=sharing) containing the project backup. To reproduce the issue, export the project dataset and follow the code in this gist: https://gist.github.com/camkisailus/5bfeedb8a3e79fd91e7b118e54e7e43b

The code is best run in a python notebook.

**Comment by bsekachev** [comment] 2024-05-24 11:27
- Upgrade guide https://docs.cvat.ai/docs/administration/advanced/upgrade_guide/

All data will stay as is after upgrade. Additional actions are not required, but backup is nevertheless recommended. 
And just note, that downgrade sometimes not possible as database migrations are one side directed. But backup may be useful here.

**Comment by zhiltsov-max** [comment] 2024-06-13 09:23
Hi, if you are exporting project annotations and the tasks are created from videos, the annotations will be merged for the frames with same names. Please try to export each task separately.

Duplicate of https://github.com/cvat-ai/cvat/issues/4993

**Comment by zhiltsov-max** [comment] 2024-07-17 08:59
Should work as expected after https://github.com/cvat-ai/cvat/pull/8171.

**Closed by zhiltsov-max** 2024-07-17 08:59 UTC
Labels: bug, need info
