### ISSUE TITLE
backup task and import it in CVAT online website

### ISSUE THREAD

**Issue by kh-diab** [cvat-ai/cvat#8227] opened 2024-07-29 13:32 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

I backup task and download it locally
when I try to create a new task from backup
it gives me error 

AttributeError: 'list' object has no attribute 'get'

[error cvat backup.docx](https://github.com/user-attachments/files/16414027/error.cvat.backup.docx)
see attached file
can you please advise how to solve it 

also I tried to export the annotation using CVAT format and coco and import it alone but it did not work

**Comment by bsekachev** [comment] 2024-07-31 09:14
May you share a backup file?

**Comment by kh-diab** [comment] 2024-07-31 11:24
it is attached in the thread
reupload it
[error.cvat.backup.docx](https://github.com/user-attachments/files/16440522/error.cvat.backup.docx)

**Comment by bsekachev** [comment] 2024-07-31 11:43
It is .docx file, it is not a backup

**Comment by bsekachev** [comment] 2024-07-31 13:09
Traceback:

```
"AttributeError: 'list' object has no attribute 'get'",

"stack": "Traceback (most recent call last):
  File \"/opt/venv/lib/python3.10/site-packages/rq/worker.py\", line 1431, in perform_job
      rv = job.perform()
        File \"/opt/venv/lib/python3.10/site-packages/rq/job.py\", line 1280, in perform
          self._result = self._execute()
            File \"/opt/venv/lib/python3.10/site-packages/rq/job.py\", line 1317, in _execute
              result = self.func(*self.args, **self.kwargs)
                File \"/home/django/cvat/apps/engine/utils.py\", line 289, in import_resource_with_clean_up_after
                  result = func(filename, *args, **kwargs)
                    File \"/usr/lib/python3.10/contextlib.py\", line 79, in inner
                      return func(*args, **kwds)
                        File \"/home/django/cvat/apps/dataset_manager/task.py\", line 947, in import_task_annotations
                          task.import_annotations(f, importer, conv_mask_to_poly=conv_mask_to_poly)
                    File \"/home/django/cvat/apps/dataset_manager/task.py\", line 820, in import_annotations
                        importer(src_file, temp_dir, task_data, **options)
                          File \"/home/django/cvat/apps/dataset_manager/formats/registry.py\", line 36, in __call__
                              f_or_cls(*args, **kwargs)
                                File \"/home/django/cvat/apps/dataset_manager/formats/coco.py\", line 38, in _import
                                    dataset = Dataset.import_from(src_file.name,
                                      File \"/opt/venv/lib/python3.10/site-packages/datumaro/components/dataset.py\", line 1198, in import_from
                                          env.make_extractor(src_conf.format, src_conf.url, **extractor_kwargs)
                                            File \"/opt/venv/lib/python3.10/site-packages/datumaro/components/environment.py\", line 230, in make_extractor
                                                return self.extractors.get(name)(*args, **kwargs)
                                                  File \"/opt/venv/lib/python3.10/site-packages/datumaro/plugins/coco_format/extractor.py\", line 468, in __init__
                                                      super().__init__(path, **kwargs)
                                                        File \"/opt/venv/lib/python3.10/site-packages/datumaro/plugins/coco_format/extractor.py\", line 87, in __init__
                                                           self._load_categories(
                                                             File \"/opt/venv/lib/python3.10/site-packages/datumaro/plugins/coco_format/extractor.py\", line 117, in _load_categories
                                                                 self._parse_field(json_data, \"categories\", list),
                                                                   File \"/opt/venv/lib/python3.10/site-packages/datumaro/plugins/coco_format/extractor.py\", line 303, in _parse_field
                                                                       value = ann.get(key, NOTSET)
                                                                       AttributeError: 'list' object has no attribute 'get'
```

@kh-diab I think you may remove any media files (images and videos). It looks like the issue with annotations.

@zhiltsov-max Do you have any ideas?

**Comment by zhiltsov-max** [comment] 2024-07-31 13:17
From the stack trace and the error message, I can guess that the problem is that the annotations have invalid file contents (a list instead of a dict). An example of the expected format can be found [here](https://github.com/cvat-ai/datumaro/blob/c7bc106fa454c9f700ae70493163d50b2694942b/tests/assets/coco_dataset/coco_instances/annotations/instances_train.json).

**Comment by azhavoro** [comment] 2024-09-06 11:18
Since no way to reproduce this issue has been provided and I will close the issue

**Closed by azhavoro** 2024-09-06 11:18 UTC
Labels: bug, need info
