### ISSUE TITLE
Add SAM2 for semi automatic annotation

### ISSUE THREAD

**Issue by nikste** [cvat-ai/cvat#8247] opened 2024-07-31 11:31 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Is your feature request related to a problem? Please describe.

There is a new version of sam, sam2.
This includes videos and tracking now for queried objects.
It also improves the performance in images.
Would be great to have this for semi automated annotation.

https://github.com/facebookresearch/segment-anything-2

**Comment by bsekachev** [comment] 2024-07-31 11:44
Duplicate of https://github.com/cvat-ai/cvat/issues/8231

**Closed by bsekachev** 2024-07-31 11:44 UTC
Labels: enhancement
