### ISSUE TITLE
Can not export CVAT for video annotaitons

### ISSUE THREAD

**Issue by PMazarovich** [cvat-ai/cvat#8411] opened 2024-09-06 14:44 UTC
### Actions before raising this issue

- [X] I searched the existing issues and did not find anything similar.
- [X] I read/searched [the docs](https://docs.cvat.ai/docs/)

### Steps to Reproduce

1. Create a task with single job
2. Upload annotations
3. Export annotations
4. Create a task with 10 jobs out of the same video
5. Upload annotations from (3)
6. Export annotations
7. Catch an AssertionError

https://github.com/user-attachments/assets/d527ad46-2929-46a8-a3a0-c45fa37a317c

### Expected Behavior

If I am able to export annotations from the task that contains 1 job, I have to be able to export annotations from the same task composed out of N jobs.
Now it is impossible.
Checking internally, I see that for some reason, the last frame of the track (outside=True) for several tracks are doubled, which is actually produces this error.

### Context

I can provide annotations if needed

### Environment

```Markdown
I see this both in 2.9.2 and in app.cvat.ai
```

**Comment by zhiltsov-max** [comment] 2024-09-06 15:58
Possible duplicate of https://github.com/cvat-ai/cvat/issues/6779

**Comment by Eldies** [comment] 2024-10-16 10:19
Hello! Could you please provide annotations? And also the video, if it's possible

**Closed** 2024-10-24 11:18 UTC
Labels: bug
